export enum Routes {
  authRouter = 'authRouter',
  mainRouter = 'mainRouter',
  welcome = 'welcome',
  login = 'login',
  register = 'register',
  verification = 'verification',
  test = 'test',
  otp = 'otp',
  modal = 'modal',
  paymentScreensTab = 'paymentScreensTab',
  paymentMethod = 'paymentMethod',
  AddNewCardScreen = 'AddNewCardScreen',
  cards = 'cards',
  tab = 'tab',
  home = 'home',
  discover = 'discover',
  bookmarks = 'bookmarks',
  notification = 'notification',
  account = 'account',
  search = 'search',
}

export enum StackRoutes {
  womenlists = 'womenlists',
  menlist = 'menlist',
  kidslists = 'kidslists',
  teenslist = 'teenslist',
  profile = 'profile',
  order = 'order',
}
