export enum Routes {
  authRouter = 'authRouter',
  mainRouter = 'mainRouter',
  welcome = 'welcome',
  login = 'login',
  register = 'register',
  verification = 'verification',
  test = 'test',
  otp = 'otp',
  modal = 'modal',
  paymentScreensTab = 'paymentScreensTab',
  paymentMethod = 'paymentMethod',
  AddNewCardScreen = 'AddNewCardScreen',
  cards = 'cards',
  tab = 'tab',
  home = 'home',
  discover = 'discover',
  bookmarks = 'bookmarks',
  notification = 'notification',
  account = 'account',
  search = 'search',
  itemList = 'itemList',
  filter = 'filter',
  productDetails = 'productDetails',
  cart = 'cart',
}

export enum StackRoutes {
  womenlists = 'womenlists',
  menlist = 'menlist',
  kidslists = 'kidslists',
  teenslist = 'teenslist',
  profile = 'profile',
  order = 'order',
  orderdetails = 'orderdetails',
  processing = 'processing',
  delivered = 'delivered',
  cancelled = 'cancelled',
  choosepayment = 'choosepayment',
  youraddress = 'youraddress',
  addaddress = 'addaddress',
  resetpassword = 'resetpassword',
  checkyouremail = 'checkyouremail',
  createnewpassword = 'createnewpassword',
  confirmpasswordreset = 'confirmpasswordreset',
  about = 'about',
  permission = 'permission',
  camera = 'camera',
}
